### ISSUE TITLE
spyder version

### ISSUE THREAD

**Issue by DTDwind** [desh2608/dover-lap#12]
Hello,

Thank you for this project, which has helped many people. 

However, I have noticed a minor issue in its usage. 

After installing `dover-lap` with `pip install dover-lap`, it overwrote my original `spyder` installation, resulting in a change in the output format of my scores. 

This has caused me some inconvenience. 

Would it be possible to address this issue?

**Comment by desh2608** [comment]
I think you can change the `requirements.txt` file to remove the strict 0.1.0 version for spy-der. Can you create a PR if this solves your problem?
