### ISSUE TITLE
Result depends on order of input rttms

### ISSUE THREAD

**Issue by kfmn** [desh2608/dover-lap#18]
Hi,

I made DOVERLap of two RTTMs and has found that the resulting RTTM differs significantly depending of the order of input RTTMs in the command line. Is it expected behaviour of bug? If it is expected, how can I control this process?

Best regards,
Maxim

**Comment by desh2608** [comment]
Can you show me what command you ran?

**Comment by desh2608** [comment]
Also, you should read this section: https://github.com/desh2608/dover-lap#combining-2-systems-with-dover-lap

**Comment by kfmn** [comment]
Thank you for the answer. 
I have not indeed read carefully the section about combining 2 systems. But I still don't understand why the order of input rttms may matter.
The commands I ran were:
`dover-lap rttm_out1 rttm_in1 rttm_in2`
and
`dover-lap rttm_out2 rttm_in2 rttm_in1`
And after running them I observed that rttm_out1 differs from rttm_out2 significantly. 

In my experiments DER of rttm_in2 is lower than that of rttm_in1 by about 2%. 
DER of rttm_out1 is similar to that of rttm_in1 (only a bit better but significantly worse than that of rttm_in2) while 
DER of rttm_out2 is even better then that of rttm_in2 by about 1%.

**Comment by desh2608** [comment]
Yes that is expected. We fall back to Hungarian mapping for the case of 2 RTTMs, which depends on the order of the provided inputs. You can think of it as the following situation: suppose you have 2 RTTMs (X and Y). DER computation between X and Y is not commutative, i.e., DER(X,Y) != DER(Y,X).

**Comment by kfmn** [comment]
OK, I got it. 
Answer please if the result is independent of the order for number of RTTMS >2 ? For each --label-mapping or just for greedy ?

**Comment by desh2608** [comment]
In the latest dover-lap, we sort all RTTMs by default by average DER to other RTTMs, so for N>2, it should be independent of the order. Let me know if you find otherwise.

**Comment by kfmn** [comment]
Thank you very much for clear explainations!

**Comment by kfmn** [comment]
I have just checked doverlap from 3 input rttms and found the result doesn't depend of order of inputs for greedy mapping. But still depends for hungarian mapping. 6 different permutations lead to 6 different output RTTMs. Maybe sorting is applied just for greedy and order is preserved for hungarian?

**Comment by desh2608** [comment]
Which version of dover-lap are you using?

**Comment by kfmn** [comment]
I installed it several months ago. How can I get a version number?

**Comment by kfmn** [comment]
I've found it. The version is 1.2.0. Will check latest soon

**Comment by kfmn** [comment]
I have installed version 1.3.0 (BTW, I had to build it from sources and install since pip cannot find version upper than 1.2.0)
But the situation hasn't changed. I still obtain different results with different permutation of 3 input RTTMs and hungarian mapping

**Comment by kfmn** [comment]
I have installed version 1.3.0 (BTW, I had to build it from sources and install since pip cannot find version upper than 1.2.0)
But I still obtain different results with different permutation of 3 input RTTMs and hungarian mapping
Although the difference seems to become less significant (the range of DER/JER fluctuations for 6 permutations is  about 0.2% now, it was larger before)

**Comment by desh2608** [comment]
If you can provide a minimum reproducible example, I will take a look later and try to fix.

**Comment by desh2608** [comment]
In the meantime, I have created a release for v1.3: https://pypi.org/project/dover-lap/1.3.0/

**Comment by kfmn** [comment]
[doverlap.zip](https://github.com/desh2608/dover-lap/files/11915438/doverlap.zip)
 Uploaded a small reproducible example. There are 3 files in zip, which I passed to dover-lap in different order (with --label-mapping=hungarian).
Hope you will look at them soon.

**Comment by desh2608** [comment]
@kfmn can you please check if the above PR solves your problem?

**Comment by desh2608** [comment]
The new version, which fixes this ordering issue, is available on PyPi: https://pypi.org/project/dover-lap/1.3.1/
